name: aspset-510
channels:
  - defaults
dependencies:
  - glfw=3.3.2
  - matplotlib=3.1.3
  - pip=20.0.2
  - pip:
    - glfw==1.11.1
    - opencv-python==4.2.0.34
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
