name: aspset-510
channels:
  - defaults
dependencies:
  - ezc3d=1.3.2
  - importlib_resources=1.4.0
  - numpy=1.18.1
  - pip=20.0.2
  - pytest=5.4.2
  - python=3.8.2
  - tqdm=4.46.0
  - pip:
    - -e .
    - git+https://github.com/anibali/posekit.git@22240a7d3d82b357e405df55d4d04a50d6cf96e8#egg=posekit
