name: aspset-510
channels:
  - defaults
  - conda-forge
dependencies:
  - ezc3d=1.3.2
  - importlib_resources=1.4.0
  - numpy=1.18.1
  - pip=20.0.2
  - pytest=5.4.2
  - python=3.8.2
  - tqdm=4.46.0
  - pip:
    - -e .
    - git+https://github.com/anibali/posekit.git@c9d61d5fa84b3e87dd1a7f0e99ae58aa1e4c759d#egg=posekit
